---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: data-philter
  labels:
    app: data-philter
spec:
  replicas: 1
  selector:
    matchLabels:
      app: data-philter
  template:
    metadata:
      labels:
        app: data-philter
    spec:
      containers:
        - name: data-philter
          image: iunera/philter:latest
          imagePullPolicy: Always
          env:
            - name: SPRING_PROFILES_ACTIVE
              value: "docker"
            - name: SERVER_PORT
              value: "4000"
          envFrom:
            - configMapRef:
                name: data-philter-app-env
          ports:
            - containerPort: 4000
              name: http
          volumeMounts:
            - name: data-philter-data
              mountPath: /data
      volumes:
        - name: data-philter-data
          persistentVolumeClaim:
            claimName: data-philter-data
---
apiVersion: v1
kind: Service
metadata:
  name: data-philter
spec:
  type: NodePort
  selector:
    app: data-philter
  ports:
    - name: http
      port: 4000
      targetPort: 4000
      nodePort: 30400
